from django.db import models

# Create your models here.
class reps(models.Model):
    id_reps = models.AutoField(primary_key=True)
    departamento = models.CharField(max_length=50)
    municipio = models.CharField(max_length=45)
    habi_codigo_habilitacion = models.CharField(max_length=15)
    codigo_de_habilitacion = models.CharField(max_length=15)
    numero_sede = models.CharField(max_length=4)
    sede_nombre = models.CharField(max_length=500)
    direccion = models.CharField(max_length=500)
    telefono = models.CharField(max_length=100)
    email = models.CharField(max_length=300)
    nit = models.CharField(max_length=15)
    dv_nit = models.CharField(max_length=2)
    ese = models.CharField(max_length=2)
    habilitado = models.CharField(max_length=2)
    grse_codigo = models.CharField(max_length=3)
    grse_nombre = models.CharField(max_length=100)
    serv_codigo = models.CharField(max_length=4)
    serv_nombre = models.CharField(max_length=200)
    ambulatorio = models.CharField(max_length=2)
    hospitalario = models.CharField(max_length=2)
    unidad_movil = models.CharField(max_length=2)
    domiciliario = models.CharField(max_length=2)
    otras_extramural = models.CharField(max_length=2)
    centro_referencia = models.CharField(max_length=2)
    institucion_remisora = models.CharField(max_length=2)
    complejidad_baja = models.CharField(max_length=2)
    complejidad_media = models.CharField(max_length=2)
    complejidad_alta = models.CharField(max_length=2)
    numero_sede_principal = models.CharField(max_length=4)
    nombre = models.CharField(max_length=500)
    modalidad_intramural = models.CharField(max_length=2)
    modalidad_extramural = models.CharField(max_length=2)
    modalidad_unidad_movil = models.CharField(max_length=2)
    modalidad_domiciliario = models.CharField(max_length=2)
    modalidad_jornada_salud = models.CharField(max_length=2)
    modalidad_telemedicina = models.CharField(max_length=2)
    modalidad_prestador_referencia = models.CharField(max_length=2)
    modalidad_prestador_referencia_telemedicina_interactiva = models.CharField(max_length=2)
    modalidad_prestador_referencia_telemedicina_no_interactiva = models.CharField(max_length=2)
    modalidad_prestador_referencia_tele_experticia = models.CharField(max_length=2)
    modalidad_prestador_referencia_tele_monitoreo = models.CharField(max_length=2)
    modalidad_prestador_remisor = models.CharField(max_length=2)
    modalidad_prestador_remisor_tele_experticia = models.CharField(max_length=2)
    modalidad_prestador_remisor_tele_monitoreo = models.CharField(max_length=2)
    complejidades = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "consolidado_reps"