from django.db import models

# Create your models here.
class Tablero(models.Model):
    id_gm = models.AutoField(primary_key=True)
    nit = models.IntegerField()
    nombre = models.CharField(max_length=500)
    tipo_proveedor = models.CharField(max_length=100)
    numero_contrato = models.CharField(max_length=4)
    year_contrato = models.IntegerField()
    fecha_inicio_contrato = models.DateField()
    fecha_fin_contrato = models.CharField(max_length=100)
    sucursal = models.CharField(max_length=100)
    supervisor = models.CharField(max_length=150)
    categoria_cuentas_medicas = models.CharField(max_length=50)
    codigo_de_habilitacion = models.CharField(max_length=15)
    numero_sede = models.CharField(max_length=4)
    sede_nombre = models.CharField(max_length=500)
    numero_sede_principal = models.CharField(max_length=4)
    departamento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=45)
    direccion = models.CharField(max_length=500)
    telefono = models.CharField(max_length=100)
    email = models.CharField(max_length=300)
    ese = models.CharField(max_length=2)
    serv_codigo = models.CharField(max_length=4)
    serv_nombre = models.CharField(max_length=200)
    grse_codigo = models.CharField(max_length=3)
    grse_nombre = models.CharField(max_length=100)
    modalidad_intramural = models.CharField(max_length=2)
    modalidad_unidad_movil = models.CharField(max_length=2)
    modalidad_domiciliario = models.CharField(max_length=2)
    modalidad_jornada_salud = models.CharField(max_length=2)
    telemedicina_interactiva = models.CharField(max_length=2)
    telemedicina_no_interactiva = models.CharField(max_length=2)
    modalidad_tele_experticia = models.CharField(max_length=2)
    modalidad_tele_monitoreo = models.CharField(max_length=2)
    latitud = models.DecimalField(max_digits=9, decimal_places=6)
    longitud = models.DecimalField(max_digits=9, decimal_places=6)
    m_dpto = models.CharField(max_length=100)
    m_municipio = models.CharField(max_length=45)
    class Meta:
        managed = False
        db_table = "gerencia_medica"